// Generated by Wrangler on Tue Sep 10 2024 12:58:38 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
  KV: KVNamespace;
  DEPLOYMENT_KEY: '20240812';
  ENVIRONMENT: 'prod';
}
