name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        name: [backend, frontend]
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ matrix.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: './${{ matrix.name }}/.nvmrc'

      - name: Run npm install
        run: npm ci

      - name: Run build
        run: npm run build
        env:
          PUBLIC_IMMICH_BACKEND_URL: 'PUBLIC_IMMICH_BACKEND_URL'

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ matrix.name }}
          if-no-files-found: error
          path: dist
          retention-days: 1

  merge:
    name: Merge Artifacts
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: build-output
          retention-days: 1
