name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: './web/.nvmrc'

      - name: Run npm install
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-web
          path: web/build
          retention-days: 1
