name: Destroy
on:
  pull_request_target:
    types: [closed]

env:
  tofu_version: '1.10.2'
  tg_version: '0.83.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [ 'dev', 'prod' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@707af61a6c8b4fa7f9476328c035208fba6b54d7 # v2

      - name: Install Terragrunt
        uses: eLco/setup-terragrunt@2c5116f8979bb261072ef57c97ac026cd9c27434 # v1
        with:
          terragrunt_version: ${{ env.tg_version }}

      - name: 'Install OpenTofu'
        uses: opentofu/setup-opentofu@592200bd4b9bbf4772ace78f887668b1aee8f716 # v1
        with:
          tofu_version: ${{ env.tofu_version }}
          tofu_wrapper: false

      - name: Destroy All
        working-directory: ${{ env.working_dir }}
        env:
          ENVIRONMENT: ${{ matrix.environment }}
          TF_VAR_dist_dir: ${{ github.workspace }}/dist
          TF_VAR_stage: pr-${{ github.event.number }}
          OP_SERVICE_ACCOUNT_TOKEN: ${{ matrix.environment == 'prod' && secrets.OP_TF_PROD_ENV || secrets.OP_TF_DEV_ENV }}
          working_dir: 'deployment'
        run: op run --env-file=".env" -- terragrunt run --all destroy --non-interactive -- -refresh=false

      - name: Comment
        uses: actions-cool/maintain-one-comment@4b2dbf086015f892dcb5e8c1106f5fccd6c1476b # v3
        with:
          number: ${{ github.event.number }}
          delete: true
          body-include: '<!-- web PR URL -->'
