name: Destroy
on:
  pull_request_target:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Destroy Frontend Subdomain
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          TF_STATE_POSTGRES_CONN_STR: ${{ secrets.TF_STATE_POSTGRES_CONN_STR }}
          DIST_DIR: ${{ github.workspace }}/dist
          ENVIRONMENT: dev
          VMETRICS_API_TOKEN: ${{ secrets.VMETRICS_API_TOKEN }}
          STAGE: pr-${{ github.event.number }}
          TF_VAR_pages_branch: ${{ steps.parameters.outputs.pagesBranch }}
          GITHUB_APP_INSTALLATION_ID: ${{ secrets.TF_APP_INSTALLATION_ID }}
          GITHUB_APP_ID: ${{ secrets.TF_APP_ID }}
          GITHUB_APP_PEM_FILE: ${{ secrets.TF_APP_PEM_FILE }}
          GITHUB_OWNER: ${{ secrets.TF_APP_GITHUB_OWNER }}
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tg_version: '0.58.12'
          tofu_version: '1.7.1'
          tg_dir: 'deployment/modules/'
          tg_command: 'run-all destroy -refresh=false'

      - name: Comment
        uses: actions-cool/maintain-one-comment@v3
        with:
          number: ${{ github.event.number }}
          delete: true
          body-include: '<!-- web PR URL -->'
